name: Deploy SAM Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production
    env:
      TRAIL_AWS_OIDC_ROLE: ${{ secrets.TRAIL_AWS_OIDC_ROLE }}
      TRAIL_AWS_REGION: ${{ secrets.TRAIL_AWS_REGION }}
      TRAIL_DYNAMODB_TABLE_NAME: ${{ vars.TRAIL_DYNAMODB_TABLE_NAME }}
      TRAIL_AWS_COG_POOL_ARN: ${{ secrets.TRAIL_AWS_COG_POOL_ARN }}
      TRAIL_AWS_COG_POOL_ID: ${{ secrets.TRAIL_AWS_COG_POOL_ID }}
      TRAIL_AWS_COG_POOL_CLIENT: ${{ secrets.TRAIL_AWS_COG_POOL_CLIENT }}
      TRAIL_CORS_ORIGIN: ${{ vars.TRAIL_CORS_ORIGIN }}
      TRAIL_AWS_SAM_STACK_NAME: ${{ vars.TRAIL_AWS_SAM_STACK_NAME }}
      TRAIL_LAMBDA_FUNCTION_NAME: ${{ vars.TRAIL_LAMBDA_FUNCTION_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required secrets and variables
        run: |
          missing=0
          for var in TRAIL_AWS_OIDC_ROLE TRAIL_AWS_REGION TRAIL_DYNAMODB_TABLE_NAME TRAIL_AWS_COG_POOL_ARN TRAIL_AWS_COG_POOL_ID TRAIL_AWS_COG_POOL_CLIENT TRAIL_CORS_ORIGIN TRAIL_AWS_SAM_STACK_NAME TRAIL_LAMBDA_FUNCTION_NAME; do
            if [ -z "${!var}" ] || [ "${!var}" = "None" ]; then
              echo "::error::Environment variable $var is not set or is 'None'"
              missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then
            exit 1
          fi
        shell: bash

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.TRAIL_AWS_OIDC_ROLE }}
          aws-region: ${{ env.TRAIL_AWS_REGION }}

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      - name: Build SAM application
        run: |
          cd backend
          sam build --template-file template.yaml
      - name: Deploy SAM application
        run: |
          cd backend
          sam deploy \
            --template-file template.yaml \
            --stack-name "${{ env.TRAIL_AWS_SAM_STACK_NAME }}" \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND \
            --no-confirm-changeset \
            --region "${{ env.TRAIL_AWS_REGION }}" \
            --resolve-s3 \
            --parameter-overrides \
              TableName="${{ env.TRAIL_DYNAMODB_TABLE_NAME }}" \
              CognitoUserPoolArn="${{ env.TRAIL_AWS_COG_POOL_ARN }}" \
              CognitoUserPoolId="${{ env.TRAIL_AWS_COG_POOL_ID }}" \
              CognitoUserPoolClientId="${{ env.TRAIL_AWS_COG_POOL_CLIENT }}" \
              CorsAllowedOrigin="${{ env.TRAIL_CORS_ORIGIN }}" \
              LambdaFunctionName="${{ env.TRAIL_LAMBDA_FUNCTION_NAME }}"