name: Terraform Deploy

on:
  push:
    paths:
      - 'infra/frontend/**'
      - '.github/workflows/terraform-deploy.yml'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init (with remote backend)
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=frontend/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_bucket_name: ${{ secrets.FRONTEND_BUCKET_NAME }}
          TF_VAR_cloudfront_alias_domain: ${{ secrets.FRONTEND_CLOUDFRONT_ALIAS_DOMAIN }}
          TF_VAR_certificate_domain_name: ${{ secrets.FRONTEND_CERTIFICATE_DOMAIN_NAME }}
          TF_VAR_certificate_san: ${{ secrets.FRONTEND_CERTIFICATE_SAN }}
          TF_VAR_hosted_zone_id: ${{ secrets.FRONTEND_HOSTED_ZONE_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_bucket_name: ${{ secrets.FRONTEND_BUCKET_NAME }}
          TF_VAR_cloudfront_alias_domain: ${{ secrets.FRONTEND_CLOUDFRONT_ALIAS_DOMAIN }}
          TF_VAR_certificate_domain_name: ${{ secrets.FRONTEND_CERTIFICATE_DOMAIN_NAME }}
          TF_VAR_certificate_san: ${{ secrets.FRONTEND_CERTIFICATE_SAN }}
          TF_VAR_hosted_zone_id: ${{ secrets.FRONTEND_HOSTED_ZONE_ID }}
